//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacionn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Precio_unidad { get; set; }
        public string Estado { get; set; }
    }
}
